### PR TITLE
New hero update

### PR DESCRIPTION
**Pull request by Trust**
Added Li-Ming, updated all stats. Checked travis build this time.

### CODE REVIEW

**Comment by diginc** [comment]
Thanks!

**Comment by Trust** [comment]
I'm not seeing the updates on the wiki, has that been done yet?

**Comment by diginc** [comment]
I forgot to sub tree push, should all be there now.

**Comment by ghost** [comment]
@trust hey! sorry for reaching out to you directly in here, would it be possible for you to change your username? We have mobile project called `Trust Wallet`, would be cool to have it as `trust` username.

React out to me here or via email in the profile.
Thanks

**Pull request merged**
